name: Dockerhub Continuous Deployment

on:
  push:

jobs:
  push_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          logout: true
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USER}}/cowcmd:latest
