name: miprimieracion

on:
  push:
    branches:
      - feature-**

jobs:
    lamine:
        runs-on: ubuntu-latest
        steps:
            - name: Primera accion
              run: echo "Hola mundo"